BEGIN TRANSACTION;
CREATE TABLE "productos" ("id" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, "nombre" TEXT NOT NULL, "precio" INTEGER NOT NULL);
INSERT INTO "productos" VALUES(0,'Mouse',1500);
INSERT INTO "productos" VALUES(1,'Teclado',2000);
INSERT INTO "productos" VALUES(2,'Monitor',5000);
INSERT INTO "productos" VALUES(3,'Gabinete',500);
INSERT INTO "productos" VALUES(4,'Placa de video',8000);
CREATE TABLE "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL DEFAULT (1), "username" TEXT UNIQUE NOT NULL, "password" TEXT NOT NULL, "email" TEXT UNIQUE NOT NULL, "admin" INTEGER NOT NULL DEFAULT (0));
INSERT INTO "users" VALUES(1,'admin','admin','admin@lucas.com',1);
INSERT INTO "users" VALUES(2,'Lucas','123','lucas@mail.com',0);
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('productos',4);
INSERT INTO "sqlite_sequence" VALUES('users',2);
COMMIT;
